### ISSUE TITLE
IPHONE CAN'T SERARCH THE BRIDGE

### ISSUE THREAD

**Issue by shiftxyy** [olivierguerriat/hassio-addons#3] opened 2017-07-30 02:18 UTC
THE HASS.IO VERSION IS 49.1 and the homebridge is successsfully runing. the raspberry and iphone is on the same network. but both my iphone 6s(IOS 11) and iphone 5(IOS 10) can't find the bridge.

starting version 3.2.1
Linking the homebridge config directory
Launching DBUS daemon…
Launching avahi daemon…
Launching homebridge…
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
[7/30/2017, 10:11:52 AM] Loaded plugin: homebridge-homeassistant
[7/30/2017, 10:11:52 AM] Registering platform 'homebridge-homeassistant.HomeAssistant'
[7/30/2017, 10:11:52 AM] ---
[7/30/2017, 10:11:52 AM] Loaded config.json with 0 accessories and 1 platforms.
[7/30/2017, 10:11:52 AM] ---
[7/30/2017, 10:11:53 AM] Loading 1 platforms...
[7/30/2017, 10:11:53 AM] [HomeAssistant] Initializing HomeAssistant platform...
[7/30/2017, 10:11:53 AM] [HomeAssistant] Fetching HomeAssistant devices.
[7/30/2017, 10:11:53 AM] Loading 0 accessories...
[7/30/2017, 10:11:53 AM] [HomeAssistant] Received event: ping
[7/30/2017, 10:11:53 AM] [HomeAssistant] Initializing platform accessory 'yeelight_white_34ce00811368'...
[7/30/2017, 10:11:53 AM] [HomeAssistant] Initializing platform accessory 'SRS-X88 F1842D'...
Scan this code with your HomeKit App on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 031-45-154 │     
    └────────────┘     
                       
[7/30/2017, 10:11:53 AM] Homebridge is running on port 51826.
[7/30/2017, 10:12:30 AM] [HomeAssistant] Received event: {"event_type": "state_changed", "data": {"entity_id": "sun.sun", "old_state": {"entity_id": "sun.sun", "state": "above_horizon", "attributes": {"next_dawn": "2017-07-30T21:52:33+00:00", "next_dusk": "2017-07-30T12:07:12+00:00", "next_midnight": "2017-07-30T16:59:33+00:00", "next_noon": "2017-07-30T04:59:35+00:00", "next_rising": "2017-07-30T22:17:33+00:00", "next_setting": "2017-07-30T11:42:09+00:00", "elevation": 50.54, "azimuth": 92.89, "friendly_name": "Sun"}, "last_changed": "2017-07-30T01:03:44.705369+00:00", "last_updated": "2017-07-30T02:11:30.073834+00:00"}, "new_state": {"entity_id": "sun.sun", "state": "above_horizon", "attributes": {"next_dawn": "2017-07-30T21:52:33+00:00", "next_dusk": "2017-07-30T12:07:12+00:00", "next_midnight": "2017-07-30T16:59:33+00:00", "next_noon": "2017-07-30T04:59:35+00:00", "next_rising": "2017-07-30T22:17:33+00:00", "next_setting": "2017-07-30T11:42:09+00:00", "elevation": 50.76, "azimuth": 93.02, "friendly_name": "Sun"}, "last_changed": "2017-07-30T01:03:44.705369+00:00", "last_updated": "2017-07-30T02:12:30.073664+00:00"}}, "origin": "LOCAL", "time_fired": "2017-07-30T02:12:30.073806+00:00"}
[7/30/2017, 10:13:20 AM] [HomeAssistant] Received event: ping
[7/30/2017, 10:13:30 AM] [HomeAssistant] Received event: {"event_type": "state_changed", "data": {"entity_id": "sun.sun", "old_state": {"entity_id": "sun.sun", "state": "above_horizon", "attributes": {"next_dawn": "2017-07-30T21:52:33+00:00", "next_dusk": "2017-07-30T12:07:12+00:00", "next_midnight": "2017-07-30T16:59:33+00:00", "next_noon": "2017-07-30T04:59:35+00:00", "next_rising": "2017-07-30T22:17:33+00:00", "next_setting": "2017-07-30T11:42:09+00:00", "elevation": 50.76, "azimuth": 93.02, "friendly_name": "Sun"}, "last_changed": "2017-07-30T01:03:44.705369+00:00", "last_updated": "2017-07-30T02:12:30.073664+00:00"}, "new_state": {"entity_id": "sun.sun", "state": "above_horizon", "attributes": {"next_dawn": "2017-07-30T21:52:33+00:00", "next_dusk": "2017-07-30T12:07:12+00:00", "next_midnight": "2017-07-30T16:59:33+00:00", "next_noon": "2017-07-30T04:59:35+00:00", "next_rising": "2017-07-30T22:17:33+00:00", "next_setting": "2017-07-30T11:42:09+00:00", "elevation": 50.98, "azimuth": 93.15, "friendly_name": "Sun"}, "last_changed": "2017-07-30T01:03:44.705369+00:00", "last_updated": "2017-07-30T02:13:30.075642+00:00"}}, "origin": "LOCAL", "time_fired": "2017-07-30T02:13:30.075783+00:00"}
[7/30/2017, 10:14:20 AM] [HomeAssistant] Received event: ping
[7/30/2017, 10:14:30 AM] [HomeAssistant] Received event: {"event_type": "state_changed", "d

**Comment by imanel** [comment] 2017-07-30 14:36
It looks like main reason is that `avahi-daemon` is unable to create connection:

```
Launching avahi daemon…
Jul 30 14:14:48 addon_75f7ddb0_homebridge syslog.info syslogd started: BusyBox v1.25.1
Jul 30 14:14:49 addon_75f7ddb0_homebridge daemon.info avahi-daemon[30]: Found user 'avahi' (UID 86) and group 'avahi' (GID 86).
Jul 30 14:14:49 addon_75f7ddb0_homebridge daemon.info avahi-daemon[30]: Successfully dropped root privileges.
Jul 30 14:14:49 addon_75f7ddb0_homebridge daemon.info avahi-daemon[30]: avahi-daemon 0.6.32 starting up.
Jul 30 14:14:49 addon_75f7ddb0_homebridge daemon.warn avahi-daemon[30]: WARNING: No NSS support for mDNS detected, consider installing nss-mdns!
Jul 30 14:14:49 addon_75f7ddb0_homebridge daemon.info avahi-daemon[30]: Successfully called chroot().
Jul 30 14:14:49 addon_75f7ddb0_homebridge daemon.info avahi-daemon[30]: Successfully dropped remaining capabilities.
Jul 30 14:14:49 addon_75f7ddb0_homebridge daemon.info avahi-daemon[30]: Loading service file /services/sftp-ssh.service.
Jul 30 14:14:49 addon_75f7ddb0_homebridge daemon.info avahi-daemon[30]: Loading service file /services/ssh.service.
Jul 30 14:14:49 addon_75f7ddb0_homebridge daemon.warn avahi-daemon[30]: *** WARNING: Detected another IPv4 mDNS stack running on this host. This makes mDNS unreliable and is thus not recommended. ***
Jul 30 14:14:49 addon_75f7ddb0_homebridge daemon.info avahi-daemon[30]: Joining mDNS multicast group on interface docker0.IPv4 with address 172.17.0.1.
Jul 30 14:14:49 addon_75f7ddb0_homebridge daemon.info avahi-daemon[30]: New relevant interface docker0.IPv4 for mDNS.
Jul 30 14:14:49 addon_75f7ddb0_homebridge daemon.info avahi-daemon[30]: Joining mDNS multicast group on interface wlan0.IPv4 with address 192.168.1.128.
Jul 30 14:14:49 addon_75f7ddb0_homebridge daemon.info avahi-daemon[30]: New relevant interface wlan0.IPv4 for mDNS.
Jul 30 14:14:49 addon_75f7ddb0_homebridge daemon.info avahi-daemon[30]: Network interface enumeration completed.
Jul 30 14:14:49 addon_75f7ddb0_homebridge daemon.info avahi-daemon[30]: Registering new address record for 172.17.0.1 on docker0.IPv4.
Jul 30 14:14:49 addon_75f7ddb0_homebridge daemon.info avahi-daemon[30]: Registering new address record for 192.168.1.128 on wlan0.IPv4.
Jul 30 14:14:49 addon_75f7ddb0_homebridge daemon.info avahi-daemon[30]: Withdrawing address record for 192.168.1.128 on wlan0.
Jul 30 14:14:49 addon_75f7ddb0_homebridge daemon.warn avahi-daemon[30]: Host name conflict, retrying with addon75f7ddb0homebridge-2
Jul 30 14:14:49 addon_75f7ddb0_homebridge daemon.info avahi-daemon[30]: Registering new address record for 172.17.0.1 on docker0.IPv4.
Jul 30 14:14:49 addon_75f7ddb0_homebridge daemon.info avahi-daemon[30]: Registering new address record for 192.168.1.128 on wlan0.IPv4.
Jul 30 14:14:50 addon_75f7ddb0_homebridge daemon.info avahi-daemon[30]: Withdrawing address record for 192.168.1.128 on wlan0.
Jul 30 14:14:50 addon_75f7ddb0_homebridge daemon.warn avahi-daemon[30]: Host name conflict, retrying with addon75f7ddb0homebridge-3
Jul 30 14:14:50 addon_75f7ddb0_homebridge daemon.info avahi-daemon[30]: Registering new address record for 172.17.0.1 on docker0.IPv4.
Jul 30 14:14:50 addon_75f7ddb0_homebridge daemon.info avahi-daemon[30]: Registering new address record for 192.168.1.128 on wlan0.IPv4.
Jul 30 14:14:51 addon_75f7ddb0_homebridge daemon.info avahi-daemon[30]: Withdrawing address record for 192.168.1.128 on wlan0.
Jul 30 14:14:51 addon_75f7ddb0_homebridge daemon.warn avahi-daemon[30]: Host name conflict, retrying with addon75f7ddb0homebridge-4
Jul 30 14:14:51 addon_75f7ddb0_homebridge daemon.info avahi-daemon[30]: Registering new address record for 172.17.0.1 on docker0.IPv4.
Jul 30 14:14:51 addon_75f7ddb0_homebridge daemon.info avahi-daemon[30]: Registering new address record for 192.168.1.128 on wlan0.IPv4.
```

And it continues like that for a long time. I'm currently trying to figure out what is the reason, but it's slow process.

**Comment by imanel** [comment] 2017-07-30 17:01
@olivierguerriat most probably related to https://github.com/lathiat/avahi/issues/117

**Comment by shiftxyy** [comment] 2017-07-31 01:44
I have this problem in hassbian with home assistant 050.

**Comment by johnhom1024** [comment] 2017-07-31 15:10
ME too！Sometimes when I restart homebridge in hassio , suddenly I can find it , but I had restarted.

**Comment by cuihaijun** [comment] 2017-08-01 01:01
ME too！Sometimes when I restart homebridge in hassio , suddenly I can find it , but I had restarted.

**Comment by 0xJohnX** [comment] 2017-08-01 19:26
ME too！

**Comment by marcelveldt** [comment] 2017-08-11 11:48
@olivierguerriat I think the issue is related to the avahi daemon binding to ipv6 instead of ipv4
You might want to change the avahi config to not bind to ipv6...

maybe it will work if you put this in the run.sh:

sed -i "/^use-ipv6=/s/=.*/=no/" /etc/avahi/avahi-daemon.conf

**Comment by TheFitzZZ** [comment] 2017-08-11 21:42
@marcelveldt How would I access the run.sh of homebridge? Enable the developer ssh and find it that way?

**Comment by olivierguerriat** [comment] 2017-08-15 09:22
Thanks for your suggestions, I tried them all but still couldn't make it work. However, Franck Nijhof did!

Please uninstall this add-on [and use his add-on instead](https://github.com/hassio-addons/repository/tree/master/homebridge). Your configuration should be transferred transparently.

**Closed as completed by olivierguerriat** 2017-08-15 09:22 UTC
